export const ADD_INGREDIENT = "ADD_INGREDIENT";

export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";

export const PURCHASE_BURGER_SUCCEED = "PURCHASE_BURGER_SUCCEED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";

export const PURCHASE_BURGER_INIT = "PURCHASE_BURGER_INIT";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";

export const FETCH_ORDERS_SUCCEED = "FETCH_ORDERS_SUCCEED";

export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_START = "AUTH_START";

export const AUTH_SUCCEED = "AUTH_SUCCEED";

export const AUTH_FAILED = "AUTH_FAILED";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
